name: hindam
description: Owner app for men's tailoring shops (HINDAM)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.0.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  image_picker: ^1.0.4

  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_analytics: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/abaya/
    - assets/fabrics/
    - assets/shops/
    - assets/icon/


